#!/bin/sh

. /etc/os-release
. /lib/functions/uci-defaults.sh

sed -i 's,downloads.openwrt.org,mirror.sjtu.edu.cn/openwrt,g' /etc/opkg/distfeeds.conf

uci -q batch <<-EOF
	#hostname
    set system.@system[0].hostname='MangoPi-M28K'

	# timezone
	set system.@system[0].timezone='CST-8'
	set system.@system[0].zonename='Asia/Shanghai'

	#ntp
	delete system.ntp.server
	add_list system.ntp.server='time.apple.com'
	add_list system.ntp.server='ntp.aliyun.com'
	add_list system.ntp.server='ntp.tencent.com'
	add_list system.ntp.server='ntp.ntsc.ac.cn'
EOF
uci commit system

# what can i say,this is LEDE
sed -i '/check_signature/d' /etc/opkg.conf

# diagnostics
if [ $(uci -q get luci.diag.ping) = "openwrt.org" ]; then
    uci set luci.diag.dns='www.douyin.com'
    uci set luci.diag.ping='www.douyin.com'
    uci set luci.diag.route='www.douyin.com'
    uci commit luci
fi

# firewall
[ $(grep -c shortcut_fe /etc/config/firewall) -eq '0' ] && uci set firewall.@defaults[0].flow_offloading='1'
if [ $(ifconfig -a | grep -o '^eth[^ ]*' | wc -l) -le 1 ] || [ "$OPENWRT_BOARD" = "armsr/armv8" ]; then
    uci set firewall.@zone[1].input='ACCEPT'
fi
uci set firewall.@defaults[0].input='ACCEPT'
uci commit firewall

# zram
mem_total=$(grep MemTotal /proc/meminfo | awk '{print $2}')
zram_size=$(echo | awk "{print int($mem_total*0.25/1024)}")
uci set system.@system[0].zram_size_mb="$zram_size"
uci set system.@system[0].zram_comp_algo='lz4'
uci commit system

# log level
uci set system.@system[0].conloglevel='1'
uci set system.@system[0].cronloglevel='9'
uci commit system

# install date
echo "export const revision = 'v$(date +%Y%m%d)', branch = 'LuCI openwrt-24.10';" > /usr/share/ucode/luci/version.uc
/etc/init.d/rpcd restart

# packet steering
uci -q get network.globals.packet_steering > /dev/null || {
    uci set network.globals='globals'
    uci set network.globals.packet_steering=2
    uci set network.globals.steering_flows='128'
    uci commit network
}

# nikki
uci batch << EOF
set nikki.mixin.dns_mode='redir-host'
delete nikki.mixin.ipv6
delete nikki.mixin.dns_ipv6
set nikki.mixin.fake_ip_range='28.0.0.1/8'
set nikki.mixin.ui_url='https://raw.ihtw.moe/https://github.com/Zephyruso/zashboard/archive/refs/heads/gh-pages.zip'
commit
EOF

# openwrt_core
sed -i '/openwrt_core/d' /etc/opkg/distfeeds.conf
sed -i "\$a\src/gz openwrt_core https://raw.ihtw.moe/raw.githubusercontent.com/sbwml/openwrt_core/aarch64_generic/$(grep Version /usr/lib/opkg/info/kernel.control | awk '{print $2}')" /etc/opkg/distfeeds.conf


exit 0